apiVersion: apps/v1
kind: Deployment
metadata:
  name: xception-preprocess
  namespace: mlops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xception-preprocess
  template:
    metadata:
      labels:
        app: xception-preprocess
    spec:
      runtimeClassName: nvidia
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: xception-preprocess
        image: 100.112.196.74:30002/mlops-core/xception-preprocess:b39f91f
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1