apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  namespace: mlops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-server
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      runtimeClassName: nvidia
      terminationGracePeriodSeconds: 90
      containers:
      - name: triton-server
        image: nvcr.io/nvidia/tritonserver:26.05-py3
        args: ["tritonserver", "--model-repository=s3://minio.minio.svc.cluster.local:9000/triton-model-repo", "--model-control-mode=explicit"]
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "quHCnPBfDaYU0UsV0vfM"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
      - name: triton-sidecar
        image: 100.112.196.74:30002/mlops-core/triton-sidecar:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      imagePullSecrets:
      - name: harbor-registry-secret