apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  namespace: mlops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: fastapi-server
        image: 100.112.196.74:30002/mlops-core/test-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"